common/urls.py
from django.urls import path

from common import views

app_name = 'common'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),

    path('cart/', views.CartView.as_view, name='cart_detail'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('404/', views.ErrorView.as_view(), name='404'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [

]

urlpatterns += i18n_patterns(
    path('', include('common.urls', namespace='home')),

    path('admin/', admin.site.urls),
    path('contact/', include('contact.urls', namespace='contact')),
    path('common/', include('common.urls', namespace='common')),
    path('products/', include('products.urls', namespace='products')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('user/', include('user.urls', namespace='accounts')),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'conf.views.handler404'

contact/urls.py
from django.urls import path

from contact import views

app_name = 'contact'

urlpatterns = [

    path('contact-us/', views.ContactView.as_view(), name='contact-us'),

]

contact/views.py
from django.views.generic import TemplateView


class ContactView(TemplateView):
    template_name = 'pages/contact.html'

templates/pages/about-us.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}About-us{% endblock %}

{% block body_id %}about-us{% endblock %}


{% block content %}
    <div class="main-content">
        <div id="wrapper-site">
            <div id="content-wrapper">

                <!-- breadcrumb -->
                <nav class="breadcrumb-bg">
                    <div class="container no-index">
                        <div class="breadcrumb">
                            <ol>
                                <li>
                                    <a href="{% url 'home:home' %}">
                                        <span>Home</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'home:about' %}">
                                        <span>{% trans 'About us' %}</span>
                                    </a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </nav>
                <div id="main">
                    <div class="page-home">
                        <div class="container">
                            <div class="about-us-content">

                                <h1 class="title-page">About Us</h1>
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 right">
                                        <a href="#">
                                            <img class="img-fluid" src="{% static 'img/other/1.jpg' %}" alt="#"/>
                                        </a>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 left">
                                        <div class="cms-block f-right">
                                            <h3 class="page-subheading">WHO WE ARE</h3>
                                            <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem
                                                quis biben
                                                dum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.
                                                Duis
                                                sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio
                                                sit
                                                amet nibh vultate cursus a sit amet mauris.</p>
                                            <p>Proin gravida nibh vel velit auctor aliquet. nec sagittis sem nibh id
                                                elit. Duis
                                                sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio
                                                sit
                                                amet nibh vultate cursus a sit amet mauris.</p>
                                            <a>
                                                <img class="img-fluid" src="{% static 'img/other/4.png' %}" alt="#"/>
                                                <span>Mr. kwang shang - CEO</span>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 right">
                                        <div class="cms-block f-left">
                                            <h3 class="page-subheading">WHAT WE DO</h3>
                                            <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem
                                                quis biben
                                                dum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.
                                                Duis
                                                sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio
                                                sit
                                                amet nibh vultate cursus a sit amet mauris.</p>
                                            <p>Proin gravida nibh vel velit auctor aliquet, nec sagittis sem nibh id
                                                elit. Duis
                                                sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio
                                                sit
                                                amet nibh vultate cursus a sit amet mauris.</p>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 left">
                                        <a href="#">
                                            <img class="img-fluid" src="{% static 'img/other/2.jpg' %}" alt="#"/>
                                        </a>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 right">
                                        <a href="#">
                                            <img class="img-fluid" src="{% static 'img/other/3.jpg' %}" alt="#"/>
                                        </a>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 left">
                                        <div class="cms-block f-right">
                                            <h3 class="page-subheading no-before">MEET OUR TEAM</h3>
                                            <div class="testimonials owl-carousel owl-theme owl-loaded owl-drag">
                                                <div class="item">
                                                    <div class="name">William James</div>
                                                    <div class="position">Designer - Stylish</div>
                                                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin,
                                                        lorem
                                                        quis biben dum auctor, nisi elit consequat ipsum, nec sagittis
                                                        sem
                                                        nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit
                                                        amet
                                                        mauris. Proin gravida nibh vel velit auctor aliquet. Aenean
                                                        sollicudin,
                                                        lorem quis bibendum auctor, nisi elit conse quat ipsum
                                                    </p>
                                                </div>
                                                <div class="item">
                                                    <div class="name">Seller Smith</div>
                                                    <div class="position">Web developer</div>
                                                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin,
                                                        lorem
                                                        quis biben dum auctor, nisi elit consequat ipsum, nec sagittis
                                                        sem
                                                        nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit
                                                        amet
                                                        mauris.
                                                    </p>
                                                </div>
                                                <div class="item">
                                                    <div class="name">Peter Capidal</div>
                                                    <div class="position">Front-end Developer</div>
                                                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin,
                                                        lorem
                                                        quis biben dum auctor, nisi elit consequat ipsum, nec sagittis
                                                        sem
                                                        nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit
                                                        amet
                                                        mauris. Proin gravida nibh vel velit auctor aliquet. Aenean
                                                        sollicudin,
                                                        lorem quis bibendum auctor, nisi elit conse quat ipsum
                                                    </p>
                                                </div>
                                                <div class="item">
                                                    <div class="name">David James</div>
                                                    <div class="position">Developer</div>
                                                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin,
                                                        lorem
                                                        quis biben dum auctor, nisi elit consequat ipsum, nec sagittis
                                                        sem
                                                        nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit
                                                        amet
                                                        mauris.Proin gravida nibh vel velit auctor aliquet. Aenean
                                                        sollicudin,
                                                        lorem quis bibendum auctor, nisi elit conse quat ipsum
                                                    </p>
                                                </div>
                                            </div>
                                            <div class="social-content">
                                                <div class="social">
                                                    <ul class="list-inline mb-0 justify-content-end">
                                                        <li class="list-inline-item mb-0">
                                                            <a href="https://t.me/AkhmedoV_48" target="_blank">
                                                                <i class="fa fa-facebook"></i>
                                                            </a>
                                                        </li>
                                                        <li class="list-inline-item mb-0">
                                                            <a href="https://t.me/AkhmedoV_48" target="_blank">
                                                                <i class="fa fa-twitter"></i>
                                                            </a>
                                                        </li>
                                                        <li class="list-inline-item mb-0">
                                                            <a href="https://t.me/AkhmedoV_48" target="_blank">
                                                                <i class="fa fa-google"></i>
                                                            </a>
                                                        </li>
                                                        <li class="list-inline-item mb-0">
                                                            <a href="https://t.me/AkhmedoV_48" target="_blank">
                                                                <i class="fa fa-instagram"></i>
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/contact.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}Contact{% endblock %}

{% block body_id %}contact{% endblock %}


{% block content %}
    <div class="main-content">
        <div id="wrapper-site">
            <div id="content-wrapper">

                <!-- breadcrumb -->
                <nav class="breadcrumb-bg">
                    <div class="container no-index">
                        <div class="breadcrumb">
                            <ol>
                                <li>
                                    <a href="{% url 'home:home' %}">
                                        <span>{% trans 'Home' %}</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'contact:contact-us' %}">
                                        <span>{% trans 'Contact' %}</span>
                                    </a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </nav>
                <div id="main">
                    <div class="page-home">
                        <div class="container">
                            <h1 class="text-center title-page">{% trans 'Contact Us' %}</h1>
                            <div class="row-inhert">
                                <div class="header-contact">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-email"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">{% trans 'Email' %}:</div>
                                                    <div class="contact-content">
                                                        <a href="mailto:support@domain.com">ahmedovj5016@gmail.com</a>
                                                        <br>
                                                        <a href="mailto:contact@domain.com">contact@domain.com</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-home"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">{% trans 'Address' %}:</div>
                                                    <div class="contact-content">
                                                        23 Suspendis matti, Visaosang Building
                                                        <br>District, NY Accums, North American
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex justify-content-end  last">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-phone"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">{% trans 'Hotline' %}:</div>
                                                    <div class="contact-content">
                                                        0123-456-78910
                                                        <br>0987-654-32100
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="contact-map">
                                    <div id="map">
                                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.3785754726428!2d105.78134315594316!3d21.01753304734255!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313454ab43c0c4db%3A0xdb6effebd6991106!2sKeangnam+Hanoi+Landmark+Tower!5e0!3m2!1svi!2s!4v1530175498947"
                                                allowfullscreen></iframe>
                                    </div>
                                </div>
                                <div class="input-contact">
                                    <p class="text-intro text-center">“Proin gravida nibh vel velit auctor aliquet.
                                        Aenean
                                        sollicudin, lorem quis bibendum
                                        auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio
                                        sit
                                        amet nibh vultate cursus a sit amet mauris. Proin gravida nibh vel velit auctor
                                        aliquet.”
                                    </p>

                                    <p class="icon text-center">
                                        <a href="#">
                                            <img src="{% static 'img/other/contact' %}_mess.png" alt="img">
                                        </a>
                                    </p>

                                    <div class="d-flex justify-content-center">
                                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                            <div class="contact-form">
                                                <form action="#" method="post" enctype="multipart/form-data">
                                                    <div class="form-fields">
                                                        <div class="form-group row">
                                                            <div class="col-md-6">
                                                                <input class="form-control" name="name"
                                                                       placeholder="Your name">
                                                            </div>
                                                            <div class="col-md-6 margin-bottom-mobie">
                                                                <input class="form-control" name="from" type="email"
                                                                       value="" placeholder="Your email">
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <div class="col-md-12 margin-bottom-mobie">
                                                                <input class="form-control" name="from" type="email"
                                                                       value="" placeholder="Subject">
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <div class="col-md-12">
                                                            <textarea class="form-control" name="message"
                                                                      placeholder="Message" rows="8"></textarea>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div>
                                                        <button class="btn" type="submit" name="submitMessage">
                                                            <img class="img-fl"
                                                                 src="{% static 'img/other/contact' %}_email.png"
                                                                 alt="img">Send
                                                            message
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}