common/urls.py
from django.urls import path

from common import views

app_name = 'common'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),

    path('cart/', views.CartView.as_view, name='cart_detail'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('404/', views.ErrorView.as_view(), name='404'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [

]

urlpatterns += i18n_patterns(
    path('', include('common.urls', namespace='home')),

    path('admin/', admin.site.urls),
    path('contact/', include('contact.urls', namespace='contact')),
    path('common/', include('common.urls', namespace='common')),
    path('products/', include('products.urls', namespace='products')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('user/', include('user.urls', namespace='accounts')),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'conf.views.handler404'

users/urls.py
from django.urls import path

from users import views
from users.views import verify_email

app_name = 'users'
urlpatterns = [
    path('account/', views.UserAccountView.as_view(), name='account'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    # path('logout/', views.LogoutView.as_view(), name='logout'),
    path('reset-password/', views.UserResetPasswordView.as_view(), name='reset-password'),
    # path('wishlist/', views.UserWishListView.as_view(), name='user_wish_list'),
    path('verify-email/<str:uidb64>/<str:token>/', verify_email, name='verify-email'),

]

templates/user-account.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Profile{% endblock %}
{% block body_id %}contact{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="wrap-banner">

            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="{% url 'home:home' %}">
                                    <span>{% trans 'Home' %}</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'users:user_account' %}">
                                    <span>{% trans 'My Account' %}</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>

            <div class="acount head-acount">
                <div class="container">
                    <div id="main">
                        <h1 class="title-page">{% trans 'My Account' %}</h1>
                        <div class="content" id="block-history">
                            <table class="std table">
                                <tbody>
                                <tr>
                                    <th class="first_item">{% trans 'My Name' %} :</th>
                                    <td>David James</td>
                                </tr>
                                <tr>
                                    <th class="first_item">{% trans 'Company' %} :</th>
                                    <td>TivaTheme</td>
                                </tr>
                                <tr>
                                    <th class="first_item">{% trans 'Address' %} :</th>
                                    <td>123 canberra Street, New York, USA</td>
                                </tr>
                                <tr>
                                    <th class="first_item">{% trans 'City' %} :</th>
                                    <td>New York</td>
                                </tr>
                                <tr>
                                    <th class="first_item">{% trans 'Postal/Zip Code' %} :</th>
                                    <td>10001</td>
                                </tr>
                                <tr>
                                    <th class="first_item">{% trans 'Phone' %} :</th>
                                    <td>0123456789</td>
                                </tr>
                                <tr>
                                    <th class="first_item">{% trans 'Country' %}:</th>
                                    <td>USA</td>
                                </tr>
                                </tbody>
                            </table>

                        </div>
                        <button class="btn btn-primary" data-link-action="sign-in" type="submit">
                            {% trans 'view Address' %}
                        </button>
                        <div class="order">
                            <h4>{% trans 'Order' %}
                                <span class="detail">{% trans 'History' %}</span>
                            </h4>
                            <p>{% trans 'You haven not placed any orders yet.' %}</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user-login.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Login{% endblock %}
{% block body_id %}contact{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="wrap-banner">

            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="{% url 'home:home' %}">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'users:login' %}">
                                    <span>Login</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>

        </div>

        <!-- main -->
        <div id="wrapper-site">
            <div id="content-wrapper" class="full-width">
                <div id="main">
                    <div class="container">
                        <h1 class="text-center title-page">Log In</h1>
                        <div class="login-form">
                            <form id="customer-form" action="{% url 'users:login' %}" method="post">
                                {% csrf_token %}
                                <div>
                                    <input type="hidden" name="back" value="my-account">
                                    <div class="form-group no-gutters">
                                        <input class="form-control" name="email" type="email" placeholder=" Email">
                                    </div>
                                    <div class="form-group no-gutters">
                                        <div class="input-group js-parent-focus">
                                            <input class="form-control js-child-focus js-visible-password"
                                                   name="password" type="password" value="" placeholder="Password">
                                        </div>
                                    </div>
                                    <div class="no-gutters text-center">
                                        <div class="forgot-password">
                                            <a href="{% url 'users:reset-password' %}" rel="nofollow">
                                                Forgot your password?
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix">
                                    <div class="text-center no-gutters">
                                        <input type="hidden" name="submitLogin" value="1">
                                        <button class="btn btn-primary" data-link-action="sign-in" type="submit">
                                            <a href="{% url 'home:home' %}">Sign in</a>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user-register.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Registration' %}{% endblock %}
{% block body_id %}contact{% endblock %}

{% block content %}
    <div class="main-content">
        <div class="wrap-banner">

            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="{% url 'home:home' %}">
                                    <span>{% trans 'Home' %}</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'common:about' %}">
                                    <span>{% trans 'About us' %}</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>
        </div>

        <!-- main -->
        <div id="wrapper-site">
            <div class="container">
                <div class="row">
                    <div id="content-wrapper" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 onecol">
                        <div id="main">
                            <div id="content" class="page-content">
                                <div class="register-form text-center">
                                    <h1 class="text-center title-page">{% trans 'Create Account' %}</h1>
                                    <form action="{% url 'users:register' %}" id="customer-form"
                                          class="js-customer-form" method="post">
                                        {% csrf_token %}
                                        <div>
                                            <div class="form-group">
                                                <div>
                                                    <input class="form-control" name="firstname" type="text"
                                                           placeholder="{% trans 'First name' %}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div>
                                                    <input class="form-control" name="lastname" type="text"
                                                           placeholder="{% trans 'Last name' %}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div>
                                                    <input class="form-control" name="username" type="text"
                                                           placeholder="{% trans 'Username' %}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div>
                                                    <input class="form-control" name="email" type="email"
                                                           placeholder="{% trans 'Email' %}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div>
                                                    <div class="input-group js-parent-focus">
                                                        <input class="form-control js-child-focus js-visible-password"
                                                               name="password" type="password"
                                                               placeholder="{% trans 'Password' %}">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="clearfix">
                                            <div>
                                                <button class="btn btn-primary"
                                                        data-link-action="sign-in"
                                                        type="submit"><a
                                                        href="{% url 'users:login' %}">{% trans 'Create Account' %}</a>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user-reset-password.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Reset Password{% endblock %}
{% block body_id %}contact{% endblock %}

{% block content %}
    <div class="main-content">
        <div class="wrap-banner">

            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="{% url 'home:home' %}">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'users:Reset_Password' %}">
                                    <span>User Reset Password</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>
        </div>

        <!-- main -->
        <div id="wrapper-site">
            <div class="container">
                <div class="row">
                    <div id="content-wrapper" class="onecol">
                        <div id="main">
                            <div class="page-content">
                                <form action="#" class="forgotten-password" method="post" id="customer-form">
                                    <h1 class="text-center title-page">User Reset Password</h1>
                                    <div class="form-fields text-center ">
                                        <div class="form-group center-email-fields">
                                            <div class="email">
                                                <input type="email" name="email" id="email" value=""
                                                       class="form-control" placeholder="Email address">
                                            </div>
                                            <div>
                                                <button class="form-control-submit btn btn-primary" name="submit"
                                                        type="submit">
                                                    Send reset link
                                                </button>
                                            </div>
                                        </div>
                                        <a href="{% url 'users:user_login' %}" class="account-link">
                                            <i class="fa fa-angle-left" aria-hidden="true"></i>
                                            <span class="text-center">Back to login</span>
                                        </a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}